# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c12a4dbab7705836cd0a80330c2888c9cb82d8f0836b2a91983e34231e442c1d112ce794fb8a3ddc72c66a28aa3713ec626376339295804d8416b64b14dba63d

test:
  secret_key_base: 2e8659f66992684170753e090498baaf7f2f4533149407d285ca83e80f239a07ef614b8b632d6977b54b96e4064c0d41dc4ee0498eddbb4233d04b84c95021b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
